#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path_url)

# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain "$domain"
ynh_app_setting_set $app path "$path_url"

#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies python-mysqldb

#=================================================
# CREATE A MYSQL DATABASE
#=================================================

db_name=$(ynh_sanitize_dbid $app)
ynh_app_setting_set $app db_name $db_name
ynh_mysql_setup_db $db_name $db_name

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
# Copy files to the right place
ynh_app_setting_set $app final_path $final_path
mkdir -p $final_path
sed -i "s@YUNOPATH@//$domain$path_url/@g" ../sources/menu/menu.js
cp -a ../sources/menu/* $final_path

# Setup the cli/api plugin
cp -a ../sources/moulinette/actionsmap/ynh_$app.yml /usr/share/moulinette/actionsmap/
mkdir /usr/lib/moulinette/ynh_$app
cp -a ../sources/moulinette/*.py /usr/lib/moulinette/ynh_$app/
cp -a ../sources/moulinette/locales /usr/lib/moulinette/ynh_$app/

#=================================================
# SPECIFIC SETUP
#=================================================
# Db installation
ynh_mysql_execute_file_as_root ../conf/create-mysql.sql $db_name

#=================================================


#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create $app

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# Create a dedicated php-fpm config
ynh_add_fpm_config
#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chown -R root: $final_path


#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_set $app skipped_uris "/"  
ynh_app_setting_set $app redirected_urls "{'/ynhpanel.js':'$path_url/menu.js'}"

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
service yunohost-api restart &
